$ANSIBLE_VAULT;1.1;AES256
39333937653632346232323432333033646666323864316434343966336436333330366434356633
6230663266326334383066356435346437643662656639360a383365393164626363396335383138
30303864643435323634356431623535663131623236663631326434316366653562306234373962
3836303862666131380a633864356264343838353239663261616331303366623336663664323465
65313563313461623764633939323063636464363332613538333539306264363338653231393430
62663562333933343337323466313766343464343235346634323434616330303034346563343339
65353931333064633131313965303362303564633966633635366532623236313330393761626534
34393438623361333966383333333536306435383034313831306432663665626436666166366130
6130
